version: '2'
services:
  www:
    build: ./docker/nginx
    ports:
      - "8080:80"
    links:
      - php
      - db
    volumes:
      - ./vhosts/:/etc/nginx/sites-enabled
      - ./:/app
  php:
    build: ./docker/php
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    working_dir: /app
    links:
      - db
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=vanilla_app"
      - "DB_USERNAME=vanilla"
      - "DB_PASSWORD=someRandomString"
  db:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    volumes:
     - /var/lib/pgsql
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_USER: docker

