<?php

namespace AppBundle\Repository;

/**
 * DistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySearchCriteria($criteria, $order)
    {
        $query = $this->createQueryBuilder('d');
        $parameters = [];

        foreach ($criteria as $column => $value) {
            $expresion = '=';
            $dbColumn = 'd.' . $column;

            if ('name' == $column) {
                $expresion = 'LIKE';
                $value = '%' . strtolower($value) . '%';
                $dbColumn = 'LOWER(d.' . $column . ')';
            }

            $query->andWhere($dbColumn . ' ' . $expresion . ' :' . $column);
            $parameters[$column] = $value;
        }
        $query->setParameters($parameters);

        foreach ($order as $column => $direction) {
            $query = $query->orderBy('d.' . $column, $direction);
        }

        return $query->getQuery()->getResult();
    }
}
